# Generated by Django 2.2.19 on 2021-04-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passaggi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='Enter an email', max_length=45)),
                ('encrypted_password', models.CharField(max_length=45)),
                ('admin', models.BooleanField()),
                ('active', models.BooleanField()),
            ],
        ),
    ]
