# Generated by Django 2.2.19 on 2021-04-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passaggi', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typevehicles',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
