# Generated by Django 2.2.19 on 2021-04-02 10:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('passaggi', '0005_auto_20210402_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('scores', models.IntegerField()),
                ('count', models.IntegerField()),
                ('total', models.IntegerField()),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='passaggi.User')),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('conversation', models.BooleanField()),
                ('animal', models.BooleanField()),
                ('smoke', models.BooleanField()),
                ('music', models.BooleanField()),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='passaggi.User')),
            ],
        ),
    ]
