# Generated by Django 2.2.19 on 2021-04-02 11:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('passaggi', '0006_preference_scores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path_Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('departure', models.CharField(help_text='Enter the departure', max_length=100)),
                ('arrive', models.CharField(help_text='Enter the arrive', max_length=100)),
                ('data_partenza', models.DateField(help_text='Enter la data di partenza')),
                ('data_arrivo', models.DateField(help_text='Enter la data di arrivo')),
                ('ora_partenza', models.CharField(max_length=45)),
                ('ora_arrivo', models.CharField(max_length=20)),
                ('max_avalaible', models.IntegerField()),
                ('price', models.FloatField()),
                ('full', models.BooleanField()),
                ('booked', models.BooleanField()),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='passaggi.User')),
                ('vehicle_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='passaggi.Vehicle')),
            ],
        ),
    ]
