# Generated by Django 2.2.19 on 2021-04-02 11:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('passaggi', '0007_path_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path_offer',
            name='ora_arrivo',
            field=models.DateTimeField(help_text="Enter l'ora di arrivo"),
        ),
        migrations.AlterField(
            model_name='path_offer',
            name='ora_partenza',
            field=models.DateTimeField(help_text="Enter l'ora di partenza"),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('scores', models.IntegerField()),
                ('feedback', models.TextField()),
                ('title', models.CharField(max_length=45)),
                ('path_offer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='passaggi.Path_Offer')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='passaggi.User')),
            ],
        ),
    ]
