# Generated by Django 2.2.19 on 2021-04-02 12:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('passaggi', '0008_auto_20210402_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('dest_user_id', models.CharField(max_length=45)),
                ('title', models.CharField(max_length=45)),
                ('message', models.CharField(max_length=45)),
                ('read', models.BooleanField()),
                ('path_offer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='passaggi.Path_Offer')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='passaggi.User')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('booked', models.IntegerField()),
                ('path_offer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='passaggi.Path_Offer')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='passaggi.User')),
            ],
        ),
    ]
