# Generated by Django 2.2.19 on 2021-04-10 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passaggi', '0010_auto_20210406_0352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='path_offer',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='type_vehicle',
            options={'ordering': ['id']},
        ),
    ]
